---
# create datafactory user
- name: create user datafactory
  user:
    name: "{{ df_user }}"
    password: "{{ df_pwd }}"
    comment: DataFactory user
    state: present
    shell: /bin/bash
    createhome: yes
    groups:
      - docker
      - sudo

# set enviroment variables for datafactory user

- name: add enviroment variable DF_PATH 
  lineinfile:
    path: "/etc/environment"
    line: "DF_PATH={{ df_installation_path }}"

- name: add enviroment variable DF_DATA_PATH 
  lineinfile:
    path: "/etc/environment"
    line: "DF_DATA_PATH={{ df_data_root_path }}"
...