---
# create datafactory group
- name: create datafactory user group
  group:
    name: datafactory
    

# set enviroment variables for datafactory user

- name: add enviroment variable DF_PATH 
  lineinfile:
    path: "/etc/environment"
    line: "DF_PATH={{ df_installation_path }}"

- name: add enviroment variable DF_DATA_PATH 
  lineinfile:
    path: "/etc/environment"
    line: "DF_DATA_PATH={{ df_data_root_path }}"
...