---
# create datafactory user
- name: create user datafactory
  user:
    name: "{{ df_user }}"
    password: "{{ df_pwd }}"
    comment: DataFactory user
    state: present
    shell: /bin/bash
    createhome: yes
    groups:
      - docker
      - sudo

# set enviroment variables for datafactory user
- name: add enviroment variable DF_DB_PROPERTIES 
  lineinfile:
    path: "/etc/environment"
    line: "DF_DB_PROPERTIES={{ df_db_properties }}"

- name: add enviroment variable DF_OUTPUT_PATH 
  lineinfile:
    path: "/etc/environment"
    line: "DF_OUTPUT_PATH={{ df_output_path }}"

- name: add enviroment variable DF_ANON_OUTPUT_PATH
  lineinfile:
    path: "/etc/environment"
    line: "DF_ANON_OUTPUT_PATH={{ df_anon_output_path }}"

- name: add enviroment variable DF_SOURCE_PATH
  lineinfile:
    path: "/etc/environment"
    line: "DF_SOURCE_PATH={{ df_source_path }}"

- name: add enviroment variable MIPMAP_PREPROCESS
  lineinfile:
    path: "/etc/environment"
    line: "MIPMAP_PREPROCESS={{ mipmap_preprocess }}"

- name: add enviroment variable MIPMAP_CAPTURE
  lineinfile:
    path: "/etc/environment"
    line: "MIPMAP_CAPTURE={{ mipmap_capture }}"

- name: add enviroment variable MIPMAP_HARMONIZE
  lineinfile:
    path: "/etc/environment"
    line: "MIPMAP_HARMONIZE={{ mipmap_harmonize }}"

- name: add enviroment variable MIPMAP_EXPORT
  lineinfile:
    path: "/etc/environment"
    line: "MIPMAP_EXPORT={{ mipmap_export }}"
...