---
# Create Data Factory folders
- name: create DataFactory config folder 
  file:
    path: "{{ df_installation_path }}"
    state: directory
    group: "{{ df_user }}"
    recurse: yes

# run 
- name: clone datafactory repo template
  git:
    repo: https://github.com/aueb-wim/ehr-datafactory-template.git
    dest: "{{ df_installation_path }}"

- name: update property rights for DataFactory config folder 
  file:
    path: "{{ df_installation_path }}"
    state: directory
    group: "{{ df_user }}"
    mode: u=rwx,g=rwx,o=rw
    recurse: yes

- name: create DataFactory data folder 
  file:
    path: "{{ df_data_root_path }}"
    state: directory
    group: "{{ df_user }}"
    mode: u=rwx,g=rwx,o=rw
    recurse: yes

- name: create DataFactory EHR folder 
  file:
    path: "{{ df_ehr_path }}"
    state: directory
    mode: u=rwx,g=rwx,o=rw
    group: "{{ df_user }}"
    recurse: yes

- name: create DataFactory EHR data input folder 
  file:
    path: "{{ df_ehr_input_path }}"
    state: directory
    group: "{{ df_user }}"
    mode: u=rwx,g=rwx,o=rw
    recurse: yes

- name: create DataFactory imaging data input folder 
  file:
    path: "{{ df_imaging_source_path }}"
    state: directory
    group: "{{ df_user }}"
    mode: u=rwx,g=rwx,o=rw
    recurse: yes

- name: create DataFactory raw NIFTI  data input folder 
  file:
    path: "{{ df_nmm_nifti_raw_input }}"
    state: directory
    group: "{{ df_user }}"
    mode: u=rwx,g=rwx,o=rw
    recurse: yes

- name: create DataFactory NIFTI  data input folder 
  file:
    path: "{{ df_nmm_nifti_input }}"
    state: directory
    group: "{{ df_user }}"
    mode: u=rwx,g=rwx,o=rw
    recurse: yes

- name: create DataFactory raw DICOM data input folder 
  file:
    path: "{{ df_nmm_dicom_raw_input }}"
    state: directory
    mode: u=rwx,g=rwx,o=rw
    group: "{{ df_user }}"
    recurse: yes

- name: create DataFactory DICOM data input folder 
  file:
    path: "{{ df_nmm_dicom_input }}"
    state: directory
    mode: u=rwx,g=rwx,o=rw
    group: "{{ df_user }}"
    recurse: yes

- name: create DataFactory SPM12 output folder 
  file:
    path: "{{ df_nmm_spm12_output }}"
    state: directory
    mode: u=rwx,g=rwx,o=rw
    group: "{{ df_user }}"
    recurse: yes
    
- name: create DataFactory data output folder 
  file:
    path: "{{ df_output_path }}"
    state: directory
    mode: u=rwx,g=rwx,o=rw
    group: "{{ df_user }}"
    recurse: yes

- name: create DataFactory anonymized data output folder 
  file:
    path: "{{ df_anon_output_path }}"
    state: directory
    mode: u=rwx,g=rwx,o=rw
    group: "{{ df_user }}"
    recurse: yes

# Create folders and tranform template files

- name: setting up config.json 
  template:
    src: config.json.j2
    dest: "{{ df_config_path }}"


