---
# install python pip
- name: install python pip
  apt:
    name: python-pip


#- name: install python packages
#  pip:
#    requirements: "{{ df_requirements_path }}"

#- name: update bash scripts and db properties files from config.json
#  command: chdir=/opt/DataFactory python2 update_files.py


# Create mipmap i2b2 databases
#- name: creating mipmap databases 
#  command: chdir=/opt/DataFactory sh build_dbs.sh all


